apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-oda-dispatcher
spec:
  replicas: 1
  selector:
    matchLabels:
      run: dev-oda-dispatcher
  template:
    metadata:
      labels:
        run: dev-oda-dispatcher
    spec:
      containers:
      - name: dev-oda-dispatcher
        image: odahub/vo-interface:latest
        imagePullPolicy: Never  # or IfNotPresent
        env:
        - name: DISPATCHER_GUNICORN
          value: "no"
        - name: DISPATCHER_CONFIG_FILE
          value: "/dispatcher/conf/conf.d/osa_data_server_conf.yml"
        volumeMounts:
        - name: dispatcher-config
          mountPath: /dispatcher/conf/conf.d
      - name: dispatcher-postgresql
        image: odahub/dispatcher-postgresql:latest
        imagePullPolicy: Never  # or IfNotPresent
        env:
        - name: POSTGRES_USER
          value: "postgres"
        # TODO: What is the best approach to pass the password? In theory, it is available inside the confgiuration file of the dispatcher
        - name: POSTGRES_PASSWORD
          value: ""
        - name: POSTGRES_DB
          value: "gallery_dev_prod_no_views"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: dispatcher-config
        hostPath:
          path: /dispatcher/conf/conf.d
      - name: postgres-data
        hostPath:
          path: /postgres_data
---
apiVersion: v1
kind: Service
metadata:
  name: dev-oda-dispatcher-service
  labels:
    run: dev-oda-dispatcher
spec:
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
  selector:
    run: dev-oda-dispatcher