# Use the official PostgreSQL 16.4 image as the base image
FROM  bitnami/postgresql:16.4.0-debian-12-r28

USER root

RUN apt-get update && apt-get install -y vim \
                                         build-essential \ 
                                         software-properties-common \
                                         git \
                                         make \
                                         gcc \
                                         postgresql-server-dev-all \
                                         bison \
                                         byacc \
                                         clang-13

                                         
# Install the PostgreSQL extension for pgsphere
RUN git clone --branch aiprdbms16 https://github.com/kimakan/pgsphere.git /pgsphere
                                         

RUN cd /pgsphere && \
make USE_PGXS=1 PG_CONFIG=/usr/bin/pg_config
RUN cd /pgsphere && \
make USE_PGXS=1 PG_CONFIG=/usr/bin/pg_config install

# get the pgloader tool and use it to load the data from the gallery DB onto the Postgres DB
RUN git clone https://github.com/dimitri/pgloader.git /pgloader

USER 1001