# Use the official PostgreSQL 16.4 image as the base image
FROM postgres:16.4-bullseye

RUN apt-get update && apt-get install -y build-essential software-properties-common
RUN apt-get update && apt-get install -y vim git make gcc-9 postgresql-server-dev-16 bison byacc && rm -rf /var/lib/apt/lists/*

# Install the PostgreSQL extension for pgsphere
RUN git clone --branch aiprdbms16 https://github.com/kimakan/pgsphere.git /pgsphere

RUN cd /pgsphere && \
    make USE_PGXS=1 PG_CONFIG=/usr/bin/pg_config
RUN cd /pgsphere && \
    make USE_PGXS=1 PG_CONFIG=/usr/bin/pg_config install
